"""Automatically fetch B-roll videos from Pexels + Pixabay.

The engine owns VIDEO assets; the user continues to provide/generate image assets.

Usage:
    set PEXELS_API_KEY=...
    set PIXABAY_API_KEY=...
    python tools/fetch-footage.py

At least one key is required. When both are present, both providers are queried
and the best candidate is selected using duration, resolution, aspect ratio,
and provider result order. Downloads are stored locally in
video/public/footage/ and a provenance manifest is written to
video/src/footage.json.

A beat is a stock-video beat when it has module=footage or an explicit footage
field. This preserves the current plan->render architecture: kinetic/text/data
beats remain generated by the existing Remotion scenes, while physical B-roll
is automatically sourced.

The script is idempotent and cache-friendly: existing beat assets are skipped
unless --force is supplied. API responses are cached for 24h under
video/out/footage-cache/ to reduce repeated API calls.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "video/src/script.json"
OUT = ROOT / "video/public/footage"
MANIFEST = ROOT / "video/src/footage.json"
CACHE = ROOT / "video/out/footage-cache"

PEXELS_VIDEO_API = "https://api.pexels.com/v1/videos/search"
PIXABAY_VIDEO_API = "https://pixabay.com/api/videos/"
CACHE_TTL = 24 * 60 * 60


def request_json(url: str, *, headers: dict[str, str] | None = None) -> Any:
    req = urllib.request.Request(url, headers=headers or {})
    with urllib.request.urlopen(req, timeout=30) as res:
        return json.load(res)


def cached_json(cache_key: str, loader) -> Any:
    CACHE.mkdir(parents=True, exist_ok=True)
    path = CACHE / f"{hashlib.sha256(cache_key.encode()).hexdigest()}.json"
    if path.exists() and time.time() - path.stat().st_mtime < CACHE_TTL:
        return json.loads(path.read_text(encoding="utf8"))
    data = loader()
    path.write_text(json.dumps(data), encoding="utf8")
    return data


def normalize_query(beat: dict[str, Any]) -> str:
    """Create a stock-search query from the explicit footage field first.

    If footage is omitted, visual/reveal/VO provide a safe fallback. The
    optional `footage_query` field can be used when the script writer wants a
    precise stock phrase without changing the editorial copy.
    """
    explicit = str(beat.get("footage_query") or beat.get("footage") or "").strip()
    if explicit:
        query = explicit
    else:
        source = " ".join(str(beat.get(k) or "") for k in ("visual", "reveal", "vo"))
        query = re.sub(r"[^\w\s-]", " ", source)

    stop = {
        "the", "and", "then", "with", "onto", "page", "one", "two", "three",
        "hold", "still", "across", "words", "lands", "single", "big", "number",
        "card", "visual", "camera", "motion", "beats", "could", "have", "been",
        "would", "they", "them", "their", "that", "this", "from", "into",
        "over", "under", "while", "just", "back", "all", "more", "very",
    }
    words = [w for w in re.findall(r"[A-Za-z0-9-]+", query.lower()) if w not in stop]
    return " ".join(words[:8])


def choose_file(files: list[dict[str, Any]], *, portrait: bool, target_long_edge: int) -> dict[str, Any] | None:
    valid = [
        f for f in files
        if f.get("url") and int(f.get("width") or 0) and int(f.get("height") or 0)
    ]
    if not valid:
        return None

    def score(f: dict[str, Any]) -> tuple:
        width = int(f["width"])
        height = int(f["height"])
        long_edge = max(width, height)
        is_portrait = height > width
        orientation_penalty = 0 if is_portrait == portrait else 1
        resolution_penalty = 0 if long_edge >= target_long_edge else 1
        distance = abs(long_edge - target_long_edge)
        return (orientation_penalty, resolution_penalty, distance)

    return sorted(valid, key=score)[0]


def pexels_search(query: str, key: str, *, portrait: bool) -> list[dict[str, Any]]:
    params = urllib.parse.urlencode({
        "query": query,
        "orientation": "portrait" if portrait else "landscape",
        "size": "large",
        "per_page": 20,
    })
    url = f"{PEXELS_VIDEO_API}?{params}"
    data = cached_json(
        f"pexels:{url}",
        lambda: request_json(url, headers={"Authorization": key}),
    )
    results: list[dict[str, Any]] = []
    for video in data.get("videos", []):
        files = [
            {
                "url": f.get("link"),
                "width": f.get("width"),
                "height": f.get("height"),
                "quality": f.get("quality"),
            }
            for f in video.get("video_files", [])
            if f.get("file_type") == "video/mp4"
        ]
        chosen = choose_file(files, portrait=portrait, target_long_edge=1920)
        if chosen:
            results.append({
                "provider": "pexels",
                "id": video.get("id"),
                "source_url": video.get("url"),
                "creator": (video.get("user") or {}).get("name"),
                "duration": float(video.get("duration") or 0),
                "file": chosen,
            })
    return results


def pixabay_search(query: str, key: str, *, portrait: bool) -> list[dict[str, Any]]:
    params = urllib.parse.urlencode({
        "key": key,
        "q": query,
        "video_type": "film",
        "safesearch": "true",
        "order": "popular",
        "per_page": 20,
        "min_width": 1280,
        "min_height": 720,
    })
    url = f"{PIXABAY_VIDEO_API}?{params}"
    data = cached_json(
        f"pixabay:{url}",
        lambda: request_json(url, headers={"User-Agent": "video-engine/1.0"}),
    )
    results: list[dict[str, Any]] = []
    for hit in data.get("hits", []):
        files = []
        for rendition in (hit.get("videos") or {}).values():
            if rendition.get("url"):
                files.append({
                    "url": rendition.get("url"),
                    "width": rendition.get("width"),
                    "height": rendition.get("height"),
                })
        chosen = choose_file(files, portrait=portrait, target_long_edge=1920)
        if chosen:
            results.append({
                "provider": "pixabay",
                "id": hit.get("id"),
                "source_url": hit.get("pageURL"),
                "creator": hit.get("user"),
                "duration": float(hit.get("duration") or 0),
                "file": chosen,
            })
    return results


def candidate_score(item: dict[str, Any], *, want_secs: float, portrait: bool) -> tuple:
    f = item["file"]
    width, height = int(f["width"]), int(f["height"])
    long_edge = max(width, height)
    orientation_penalty = 0 if (height > width) == portrait else 1
    duration_penalty = 0 if item["duration"] >= want_secs else 1
    duration_gap = abs(item["duration"] - want_secs)
    resolution_penalty = 0 if long_edge >= 1920 else 1
    return (
        orientation_penalty,
        duration_penalty,
        resolution_penalty,
        duration_gap,
        -long_edge,
    )


def download(url: str, dest: Path) -> None:
    req = urllib.request.Request(url, headers={"User-Agent": "video-engine/1.0"})
    with urllib.request.urlopen(req, timeout=180) as res, dest.open("wb") as out:
        while True:
            chunk = res.read(1024 * 1024)
            if not chunk:
                break
            out.write(chunk)


def existing_asset(beat_no: int) -> Path | None:
    for ext in ("mp4", "webm", "mov"):
        p = OUT / f"beat-{beat_no:02d}.{ext}"
        if p.exists():
            return p
    return None


def main() -> None:
    ap = argparse.ArgumentParser(description="Fetch B-roll videos from Pexels and Pixabay")
    ap.add_argument("--force", action="store_true", help="replace existing beat videos")
    args = ap.parse_args()

    script = json.loads(SCRIPT.read_text(encoding="utf8"))
    width, height = int(script["width"]), int(script["height"])
    portrait = height >= width
    beats = [
        b for b in script.get("beats", [])
        if b.get("module") == "footage" or str(b.get("footage") or b.get("footage_query") or "").strip()
    ]

    pexels_key = os.environ.get("PEXELS_API_KEY", "").strip()
    pixabay_key = os.environ.get("PIXABAY_API_KEY", "").strip()
    if not pexels_key and not pixabay_key:
        print("No PEXELS_API_KEY or PIXABAY_API_KEY set; footage stage skipped.", file=sys.stderr)
        return

    OUT.mkdir(parents=True, exist_ok=True)
    manifest: dict[str, Any] = {}

    for beat in beats:
        n = int(beat["n"])
        have = existing_asset(n)
        if have and not args.force:
            manifest[str(n)] = {"file": f"footage/{have.name}", "status": "existing"}
            print(f"  beat {n:02d}  existing {have.name}")
            continue

        query = normalize_query(beat)
        if not query:
            print(f"  beat {n:02d}  no searchable visual query", file=sys.stderr)
            continue

        want_secs = max(0.5, float(beat.get("end", 0)) - float(beat.get("start", 0)))
        candidates: list[dict[str, Any]] = []

        if pexels_key:
            try:
                candidates.extend(pexels_search(query, pexels_key, portrait=portrait))
            except urllib.error.HTTPError as err:
                print(f"  beat {n:02d}  Pexels HTTP {err.code}", file=sys.stderr)
            except Exception as err:
                print(f"  beat {n:02d}  Pexels error: {err}", file=sys.stderr)

        if pixabay_key:
            try:
                candidates.extend(pixabay_search(query, pixabay_key, portrait=portrait))
            except urllib.error.HTTPError as err:
                print(f"  beat {n:02d}  Pixabay HTTP {err.code}", file=sys.stderr)
            except Exception as err:
                print(f"  beat {n:02d}  Pixabay error: {err}", file=sys.stderr)

        if not candidates:
            print(f"  beat {n:02d}  no video match for {query!r}", file=sys.stderr)
            continue

        best = sorted(
            candidates,
            key=lambda x: candidate_score(x, want_secs=want_secs, portrait=portrait),
        )[0]
        if have:
            have.unlink()

        dest = OUT / f"beat-{n:02d}.mp4"
        try:
            download(best["file"]["url"], dest)
        except Exception as err:
            print(f"  beat {n:02d}  download failed: {err}", file=sys.stderr)
            continue

        manifest[str(n)] = {
            "file": f"footage/{dest.name}",
            "provider": best["provider"],
            "asset_id": best["id"],
            "source_url": best["source_url"],
            "creator": best["creator"],
            "query": query,
            "duration": best["duration"],
            "width": best["file"]["width"],
            "height": best["file"]["height"],
        }
        print(f"  beat {n:02d}  {dest.name} <- {best['provider']} <- {query!r}")

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf8")
    print(f"\nfootage.json — {len(manifest)} video assets")


if __name__ == "__main__":
    main()
