import type { ComponentType } from "react";
import type { EffectName } from "../../types";
import * as Camera from "../camera";
import * as Parallax from "../parallax";
import * as Entrance from "../image-entrance";
import * as Exit from "../image-exit";
import * as Atmosphere from "../atmosphere";
import * as Color from "../color";
import * as Screen from "../screen";
import * as Draw from "../draw";
import * as Combinations from "../combinations";
import * as Finance from "../finance";
import * as Drama from "../drama";
import * as CameraEffects from "../camera-effects";
import { Placeholder } from "./Placeholder";

export const REGISTRY: Record<EffectName, ComponentType<any>> = {
  pushIn: Camera.PushIn,
  pullOut: Camera.PullOut,
  panLeft: Camera.PanLeft,
  panRight: Camera.PanRight,
  panUp: Camera.PanUp,
  panDown: Camera.PanDown,
  diagonalPan: Camera.DiagonalPan,
  slowDrift: Camera.SlowDrift,
  staticHold: Camera.StaticHold,
  microBreathing: Camera.MicroBreathing,
  pushPanLeft: Camera.PushPanLeft,
  pushPanRight: Camera.PushPanRight,
  pullPan: Camera.PullPan,
  pushTilt: Camera.PushTilt,
  diagonalPush: Camera.DiagonalPush,
  cornerToCorner: Camera.CornerToCorner,
  subjectReframe: Camera.SubjectReframe,
  faceReframe: Camera.FaceReframe,
  objectReframe: Camera.ObjectReframe,
  detailReveal: Camera.DetailReveal,

  twoLayerParallax: Parallax.TwoLayerParallax,
  threeLayerParallax: Parallax.ThreeLayerParallax,
  multiLayerParallax: Parallax.MultiLayerParallax,
  depthBasedZoom: Parallax.DepthBasedZoom,
  foregroundDrift: Parallax.ForegroundDrift,
  backgroundDrift: Parallax.BackgroundDrift,
  dolly: Parallax.Dolly,
  perspectiveShift: Parallax.PerspectiveShift,
  depthOfField: Parallax.DepthOfField,
  foregroundBlur: Parallax.ForegroundBlur,
  backgroundBlur: Parallax.BackgroundBlur,
  rackFocus: Parallax.RackFocus,

  fadeIn: Entrance.FadeIn,
  fadeInScale: Entrance.FadeInScale,
  fadeInBlur: Entrance.FadeInBlur,
  slideInLeft: Entrance.SlideInLeft,
  slideInRight: Entrance.SlideInRight,
  slideInTop: Entrance.SlideInTop,
  slideInBottom: Entrance.SlideInBottom,
  scaleIn: Entrance.ScaleIn,
  maskReveal: Entrance.MaskReveal,
  wipeReveal: Entrance.WipeReveal,
  circularReveal: Entrance.CircularReveal,
  diagonalReveal: Entrance.DiagonalReveal,
  paperReveal: Entrance.PaperReveal,
  filmBurnReveal: Entrance.FilmBurnReveal,
  lightLeakReveal: Placeholder,
  focusReveal: Entrance.FocusReveal,

  fadeOut: Exit.FadeOut,
  scaleOut: Exit.ScaleOut,
  blurOut: Exit.BlurOut,
  slideOutLeft: Exit.SlideOutLeft,
  slideOutRight: Exit.SlideOutRight,
  slideOutUp: Exit.SlideOutUp,
  slideOutDown: Exit.SlideOutDown,
  maskClose: Exit.MaskClose,
  zoomThrough: Exit.ZoomThrough,
  pullAway: Exit.PullAway,
  dipToBlack: Exit.DipToBlack,
  dipToWhite: Exit.DipToWhite,

  crossfade: Placeholder,
  hardCut: Placeholder,
  matchCut: Placeholder,
  transitionDipToBlack: Placeholder,
  transitionDipToWhite: Placeholder,
  whipPan: Placeholder,
  zoomTransition: Placeholder,
  blurTransition: Placeholder,
  lightFlash: Placeholder,
  filmBurn: Placeholder,
  paperWipe: Placeholder,
  newspaperWipe: Placeholder,
  documentWipe: Placeholder,
  shapeWipe: Placeholder,
  maskTransition: Placeholder,
  imageMorph: Placeholder,

  textFade: Placeholder,
  textSlide: Placeholder,
  textRise: Placeholder,
  textDrop: Placeholder,
  textScale: Placeholder,
  textBlurSharp: Placeholder,
  typewriter: Placeholder,
  charByChar: Placeholder,
  wordByWord: Placeholder,
  lineByLine: Placeholder,
  textMaskReveal: Placeholder,
  textWipeReveal: Placeholder,
  kinetic: Placeholder,
  wordEmphasis: Placeholder,
  numberEmphasis: Placeholder,
  oversizedNumber: Placeholder,
  fullScreenStatement: Placeholder,
  splitTypography: Placeholder,
  trackingAnimation: Placeholder,
  letterSpacingAnimation: Placeholder,
  weightChange: Placeholder,
  highlightSweep: Placeholder,
  underlineDraw: Placeholder,
  strikeThrough: Placeholder,
  textDisplacement: Placeholder,
  textStagger: Placeholder,
  textStacking: Placeholder,
  textCollision: Placeholder,
  textSnapping: Placeholder,

  stockChart: Finance.stockChart,
  lineGraphDraw: Finance.lineGraphDraw,
  barChartGrowth: Finance.barChartGrowth,
  barChartCollapse: Finance.barChartCollapse,
  percentageCounter: Finance.percentageCounter,
  dollarCounter: Finance.dollarCounter,
  revenueCounter: Finance.revenueCounter,
  debtCounter: Finance.debtCounter,
  marketCapCounter: Finance.marketCapCounter,
  stockPriceCounter: Finance.stockPriceCounter,
  countdown: Finance.countdown,
  upDownIndicator: Finance.upDownIndicator,
  arrowAnimation: Finance.arrowAnimation,
  circularPercentage: Finance.circularPercentage,
  progressBar: Finance.progressBar,
  timeline: Finance.timeline,
  marketTicker: Finance.marketTicker,
  priceFluctuation: Finance.priceFluctuation,
  numberRolling: Finance.numberRolling,
  decimalCounter: Finance.decimalCounter,
  financialDashboard: Finance.financialDashboard,
  portfolioVisualization: Finance.portfolioVisualization,
  balanceSheetReveal: Finance.balanceSheetReveal,

  computerScreen: Screen.ComputerScreen,
  monitorChart: Screen.MonitorChart,
  monitorTicker: Screen.MonitorTicker,
  monitorNumbers: Screen.MonitorNumbers,
  tvScreen: Screen.TVScreen,
  phoneScreen: Screen.PhoneScreen,
  phoneNotification: Screen.PhoneNotification,
  laptopScreen: Screen.LaptopScreen,
  atmDisplay: Screen.ATMDisplay,
  billboard: Screen.Billboard,
  digitalSign: Screen.DigitalSign,
  calculatorNumbers: Screen.CalculatorNumbers,
  digitalClock: Screen.DigitalClock,
  newsHeadline: Screen.NewsHeadline,
  newspaperHighlight: Screen.NewspaperHighlight,
  documentHighlight: Screen.DocumentHighlight,
  mapRoute: Screen.MapRoute,
  gpsMovement: Screen.GpsMovement,
  cursorMovement: Screen.CursorMovement,
  typingSimulation: Screen.TypingSimulation,
  scrollingWebpage: Screen.ScrollingWebpage,

  handDrawnCircle: Draw.HandDrawnCircle,
  arrowDraw: Draw.ArrowDraw,
  drawUnderline: Draw.DrawUnderline,
  graphDraw: Draw.GraphDraw,
  mapRouteDraw: Draw.MapRouteDraw,
  connectionLine: Draw.ConnectionLine,
  boxOutline: Draw.BoxOutline,
  scribble: Draw.Scribble,
  bracket: Draw.Bracket,
  timelineLine: Draw.TimelineLine,
  signatureDraw: Draw.SignatureDraw,

  faceCrop: Placeholder,
  objectCrop: Placeholder,
  documentCrop: Placeholder,
  logoCrop: Placeholder,
  moneyCrop: Placeholder,
  computerCrop: Placeholder,
  graphCrop: Placeholder,
  backgroundCrop: Placeholder,
  extremeCloseUp: Placeholder,
  wideShot: Placeholder,
  mediumShot: Placeholder,
  detailShot: Placeholder,

  spotlight: Placeholder,
  circularSpotlight: Placeholder,
  darkenSurroundings: Placeholder,
  blurSurroundings: Placeholder,
  brightenSubject: Placeholder,
  colorIsolate: Placeholder,
  outlineSubject: Placeholder,
  glowSubject: Placeholder,
  zoomSubject: Placeholder,
  movingSpotlight: Placeholder,
  magnifyingGlass: Placeholder,
  focusPull: Placeholder,

  vignette: Atmosphere.Vignette,
  grain: Atmosphere.Grain,
  dust: Atmosphere.Dust,
  lightSweep: Atmosphere.LightSweep,
  lightLeak: Atmosphere.LightLeak,
  screenGlow: Atmosphere.ScreenGlow,
  flicker: Atmosphere.Flicker,
  exposurePulse: Atmosphere.ExposurePulse,
  shadowMovement: Atmosphere.ShadowMovement,
  fog: Atmosphere.Fog,
  mist: Atmosphere.Mist,
  reflection: Atmosphere.Reflection,
  lensFlare: Atmosphere.LensFlare,
  filmTexture: Atmosphere.FilmTexture,
  brightnessBreathing: Atmosphere.BrightnessBreathing,

  newspaperSlide: Placeholder,
  newspaperZoom: Placeholder,
  headlineHighlight: Placeholder,
  articleCrop: Placeholder,
  docTextUnderline: Placeholder,
  redCircle: Placeholder,
  documentStack: Placeholder,
  paperShuffle: Placeholder,
  paperTear: Placeholder,
  documentReveal: Placeholder,
  photocopyEffect: Placeholder,
  archiveEffect: Placeholder,
  stampAnimation: Placeholder,
  dateStamp: Placeholder,
  filingCard: Placeholder,

  locationPin: Placeholder,
  pinDrop: Placeholder,
  routeDrawing: Placeholder,
  countryHighlight: Placeholder,
  cityHighlight: Placeholder,
  connectionLines: Placeholder,
  flightPath: Placeholder,
  expansion: Placeholder,
  marketSpread: Placeholder,
  geographicZoom: Placeholder,
  mapPushIn: Placeholder,

  chartCrash: Drama.ChartCrash,
  chartExplosion: Drama.ChartExplosion,
  numberShock: Drama.NumberShock,
  screenGlitch: Drama.ScreenGlitch,
  digitalDistortion: Drama.DigitalDistortion,
  imageShake: Drama.ImageShake,
  microJitter: Drama.MicroJitter,
  flash: Drama.Flash,
  redWarningPulse: Drama.RedWarningPulse,
  crackReveal: Drama.CrackReveal,
  dramaPaperTear: Drama.dramaPaperTear,
  smoke: Drama.Smoke,
  particleBurst: Drama.ParticleBurst,
  rapidZoom: Drama.RapidZoom,
  freezeFrame: Drama.FreezeFrame,

  blackAndWhite: Color.BlackAndWhite,
  toColor: Color.ToColor,
  desaturation: Color.Desaturation,
  saturationPulse: Color.SaturationPulse,
  warmToCold: Color.WarmToCold,
  coldToWarm: Color.ColdToWarm,
  darkToBright: Color.DarkToBright,
  brightToDark: Color.BrightToDark,
  blurToSharp: Color.BlurToSharp,
  sharpToBlur: Color.SharpToBlur,
  contrastPulse: Color.ContrastPulse,
  exposureChange: Color.ExposureChange,
  filmLook: Color.FilmLook,
  archiveLook: Color.ArchiveLook,

  handheld: CameraEffects.Handheld,
  cameraShake: CameraEffects.CameraShake,
  dollyMove: CameraEffects.DollyMove,
  dollyZoom: CameraEffects.DollyZoom,
  crane: CameraEffects.Crane,
  cameraTilt: CameraEffects.CameraTilt,
  cameraRoll: CameraEffects.CameraRoll,
  orbit: CameraEffects.Orbit,
  cameraFocusPull: CameraEffects.CameraFocusPull,
  lensBreathing: CameraEffects.LensBreathing,
  cameraVibration: CameraEffects.CameraVibration,

  financePortrait: Combinations.FinancePortrait,
  stockMarketScene: Combinations.StockMarketScene,
  financialCollapse: Combinations.FinancialCollapse,
  historicalEvent: Combinations.HistoricalEvent,
  billionDollarReveal: Combinations.BillionDollarReveal,
};